title: "migueldnt.dev"
description: >-
    Software Developer. #GIS #Marketing 

url: "https://migueldnt.dev"

#theme: minima
plugins:
    - jekyll-feed
    - jekyll-seo-tag

exclude:
    - README.md
    - .jekyll-cache
    - docker-compose.yml
    - docker-compose-dev.yml    
    - .gitkeep