#run service to localhost:4000
version: "3"

services:
  jekyll:
    image: jekyll/jekyll:4.0
    command: "jekyll server --livereload"
    ports:
      - "4000:4000"
    volumes: 
      - ".:/srv/jekyll/"